import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import ParentProvider from "./Providers/ParentProvider";
import { UserProvider } from "./Providers/UserDataContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
                 <ParentProvider>
        <ThemeProvider attribute="class" defaultTheme="light">
          <div className="min-h-screen bg-linear-to-br from-primary/5 via-secondary/5 to-background">
              <UserProvider>
            <Navbar />
            <main className="w-full flex flex-1 flex-col items-center bg-background min-h-screen ">
                {children}
            </main>
              </UserProvider>
          </div>
        </ThemeProvider>
                </ParentProvider>
      </body>
    </html>
  );
}
