import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import { ThemeProvider } from "next-themes";
import TanStackProvider from "./Providers/TanStackProvider";
import { Toaster } from "sonner";

import ParentProvider from "./Providers/ParentProvider";
import TokenContextProvider from "./Providers/TokenContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider attribute="class" defaultTheme="light">
              <TanStackProvider>
          <div className="min-h-screen bg-linear-to-br from-primary/5 via-secondary/5 to-background">
            <TokenContextProvider>
            <Navbar />
            <main className="w-full flex flex-1 flex-col items-center bg-background">
                 <ParentProvider>
                {children}
                </ParentProvider>
            </main>
              </TokenContextProvider>
          </div>
                  </TanStackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
