# Generated by Django 6.0.2 on 2026-06-05 03:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Flag indicating the active term. Only one term should have this set to True.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalTeam',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('project_type', models.CharField(choices=[('COURSE', 'Course Project'), ('GRADUATION', 'Graduation Project')], default='COURSE', max_length=20)),
                ('philosophy', models.CharField(choices=[('KANBAN', 'Kanban'), ('SPRINT', 'Sprint'), ('MILESTONE', 'Milestone')], default='KANBAN', max_length=20)),
                ('status', models.CharField(choices=[('FORMING', 'Forming'), ('PENDING_SUPERVISORS', 'Pending Supervisors'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='FORMING', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('board_config', models.JSONField(blank=True, default=dict, help_text='Free-form JSON configuration for the team board (columns, swimlanes, etc).')),
                ('is_locked', models.BooleanField(default=False, help_text='When True, the team structure is locked and edits require re-approval.')),
                ('is_recruiting', models.BooleanField(default=True, help_text='Whether the team is currently open to new members.')),
                ('max_capacity', models.PositiveIntegerField(default=5, help_text='Maximum number of accepted student members.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.academicterm')),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.subject')),
            ],
            options={
                'verbose_name': 'historical Team',
                'verbose_name_plural': 'historical Teams',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('project_type', models.CharField(choices=[('COURSE', 'Course Project'), ('GRADUATION', 'Graduation Project')], default='COURSE', max_length=20)),
                ('philosophy', models.CharField(choices=[('KANBAN', 'Kanban'), ('SPRINT', 'Sprint'), ('MILESTONE', 'Milestone')], default='KANBAN', max_length=20)),
                ('status', models.CharField(choices=[('FORMING', 'Forming'), ('PENDING_SUPERVISORS', 'Pending Supervisors'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='FORMING', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('board_config', models.JSONField(blank=True, default=dict, help_text='Free-form JSON configuration for the team board (columns, swimlanes, etc).')),
                ('is_locked', models.BooleanField(default=False, help_text='When True, the team structure is locked and edits require re-approval.')),
                ('is_recruiting', models.BooleanField(default=True, help_text='Whether the team is currently open to new members.')),
                ('max_capacity', models.PositiveIntegerField(default=5, help_text='Maximum number of accepted student members.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='projects.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='projects.academicterm')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', 'Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_invite', models.BooleanField(default=True, help_text='True when the row was created as a supervisor/leader invite, False on student self-join.')),
                ('team_project_type', models.CharField(choices=[('COURSE', 'Course Project'), ('GRADUATION', 'Graduation Project')], default='COURSE', editable=False, help_text='Denormalized copy of team.project_type; required for the database-level uniqueness rule.', max_length=20)),
                ('team_is_deleted', models.BooleanField(default=False, editable=False, help_text='Denormalized copy of team.is_deleted; required for the database-level uniqueness rule.')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammembership_set', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammember_set', to='projects.team')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams_as_member', through='projects.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeamSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DOCTOR', 'Doctor'), ('TA', 'Teaching Assistant')], default='DOCTOR', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_teams', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamsupervisor_set', to='projects.team')),
            ],
            options={
                'verbose_name': 'Team Supervisor',
                'verbose_name_plural': 'Team Supervisors',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='teams_as_supervisor', through='projects.TeamSupervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['student', 'status'], name='projects_te_student_217898_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'student'), name='uniq_teammember_team_student'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED'), ('team_is_deleted', False), ('team_project_type', 'GRADUATION')), fields=('student',), name='uniq_active_graduation_membership_per_student'),
        ),
        migrations.AddIndex(
            model_name='teamsupervisor',
            index=models.Index(fields=['supervisor', 'status'], name='projects_te_supervi_9dacf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamsupervisor',
            constraint=models.UniqueConstraint(fields=('team', 'supervisor'), name='uniq_teamsupervisor_team_supervisor'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['term', 'project_type'], name='projects_te_term_id_8caa3e_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['status'], name='projects_te_status_47baa8_idx'),
        ),
    ]
