# Generated by Django 6.0.2 on 2026-06-15 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'leader')), fields=('project',), name='unique_project_leader'),
        ),
    ]
