# Generated by Django 6.0.2 on 2026-06-15 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_academicyear_category_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('credit_hours', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='projects_su_code_31abd8_idx')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.subject'),
        ),
    ]
