# Generated by Django 6.0.2 on 2026-06-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_subject_project_subject'),
        ('users', '0008_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='archive_tags',
        ),
        migrations.AddField(
            model_name='project',
            name='archive_tags',
            field=models.ManyToManyField(blank=True, related_name='archive_tagged_projects', to='users.skill'),
        ),
    ]
