# Generated by Django 6.0.2 on 2026-06-20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_actual_hours_task_estimated_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='position',
        ),
        migrations.AlterField(
            model_name='task',
            name='story_points',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
