# Generated by Django 6.0.2 on 2026-06-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('request', 'Request'), ('approval', 'Approval'), ('comment', 'Comment'), ('task_assignment', 'Task assignment'), ('task_update', 'Task update'), ('feedback', 'Feedback'), ('meeting', 'Meeting'), ('deliverable_review', 'Deliverable review'), ('system', 'System')], max_length=30),
        ),
    ]
