import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import { AIChatWidget } from "@/components/ai-assistant/AIChatWidget";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import ParentProvider from "../Providers/ParentProvider";
import { UserProvider } from "../Providers/UserDataContext";
import ReactQueryProvider from "../Providers/ReactQueryProvider";
import MySessionProvider from "../Providers/MySessionProvider";
import { NextIntlClientProvider } from 'next-intl';
import NotificationCountProvider from "../Providers/NotificationCountProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "UniManage",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
   params: Promise<{ locale: string }>;
  
}>) {
    const { locale } = await params;
  const session = await getServerSession(authOptions)
  const messages = (await import(`@/messages/${locale}.json`)).default;
  return (
    <html  suppressHydrationWarning lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <NextIntlClientProvider messages={messages}>

          <MySessionProvider session={session}>
                 <ParentProvider>
        <ThemeProvider attribute="class" defaultTheme="light">
          <div className="min-h-screen   bg-background">
              <UserProvider>
            <Navbar />
<ReactQueryProvider>

            <main className="w-full flex flex-1 bg-linear-to-br from-primary/5 via-secondary/5 to-background flex-col items-center min-h-screen ">
                        <Toaster />
                        <NotificationCountProvider>

                {children}
                        <AIChatWidget />
                        </NotificationCountProvider>
            </main>
</ReactQueryProvider>
              </UserProvider>
          </div>
        </ThemeProvider>
                </ParentProvider>
          </MySessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
