# Generated by Django 6.0.2 on 2026-04-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('SUPERVISOR', 'Supervisor')], default='STUDENT', max_length=20),
        ),
    ]
