# Generated by Django 6.0.2 on 2026-05-29 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_official', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='is_professor',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='looking_for_course_project_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='looking_for_grad_project_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='max_team_capacity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='scholar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='title',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('TA', 'Teaching Assistant')], default='DOCTOR', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='expertise',
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='users.skill')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(related_name='students', to='users.skill'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='expertise',
            field=models.ManyToManyField(related_name='supervisors', to='users.skill'),
        ),
    ]
