# Generated by Django 6.0.2 on 2026-05-29 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill_remove_supervisorprofile_is_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
