# Generated by Django 6.0.2 on 2026-05-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skill_generated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('SUPERVISOR', 'Supervisor')], max_length=20, null=True),
        ),
    ]
