# Generated by Django 6.0.2 on 2026-05-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_academiclevel_department_major_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='major',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.department'),
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
